import type { Supplier } from './supplierTypes'

export const mockSuppliers: Supplier[] = [
  {
    id: 'cohen-vegetables',
    slug: 'cohen-vegetables',
    name: 'כהן ירקות למסעדות',
    logoUrl: '/ordan-logo.png',
    description: 'אספקת ירקות ופירות טריים למסעדות, בתי קפה ומטבחים מוסדיים עם ליקוט בוקר.',
    categories: ['ירקות', 'פירות', 'תוצרת טרייה'],
    phone: '03-555-0140',
    whatsappUrl: 'https://wa.me/97235550140',
    websiteUrl: '/suppliers/cohen-vegetables',
    minimumOrder: 750,
    deliveryDays: ['א׳', 'ב׳', 'ד׳', 'ה׳'],
    cityCoverage: ['חיפה', 'נתניה', 'הרצליה', 'תל אביב', 'עפולה'],
    regionIds: ['upper-galilee', 'lower-galilee', 'haifa-krayot', 'valleys', 'sharon', 'tel-aviv-center'],
    isRecommended: true,
    isVerified: true,
  },
  {
    id: 'daniel-meat-supply',
    slug: 'daniel-meat-supply',
    name: 'דניאל אספקת בשר',
    logoUrl: '/ordan-logo.png',
    description: 'חיתוך לפי דרישה, אריזה מקוררת ומשלוחים קבועים למסעדות וקייטרינג.',
    categories: ['בשר', 'עופות', 'דגים'],
    phone: '03-555-0199',
    whatsappUrl: 'https://wa.me/97235550199',
    websiteUrl: '/suppliers/daniel-meat-supply',
    minimumOrder: 1200,
    deliveryDays: ['א׳', 'ג׳', 'ה׳'],
    cityCoverage: ['תל אביב', 'ראשון לציון', 'מודיעין', 'ירושלים'],
    regionIds: ['tel-aviv-center', 'shfela', 'jerusalem-area'],
    isRecommended: true,
    isVerified: true,
  },
  {
    id: 'bakery-direct',
    slug: 'bakery-direct',
    name: 'Bakery Direct',
    logoUrl: '/ordan-logo.png',
    description: 'מאפייה מוסדית עם אספקה יומית מוקדמת לרשתות קפה ומסעדות.',
    categories: ['מאפים', 'לחמים', 'קונדיטוריה'],
    phone: '09-555-0177',
    whatsappUrl: 'https://wa.me/97295550177',
    websiteUrl: '/suppliers/bakery-direct',
    minimumOrder: 500,
    deliveryDays: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳'],
    cityCoverage: ['נתניה', 'הרצליה', 'תל אביב', 'רחובות'],
    regionIds: ['sharon', 'tel-aviv-center', 'shfela'],
    isRecommended: false,
    isVerified: true,
  },
  {
    id: 'ordan-packaging',
    slug: 'ordan-packaging',
    name: 'אורדן אריזות',
    logoUrl: '/ordan-logo.png',
    description: 'פתרונות אריזה, כלים חד פעמיים ומוצרי נייר לעסקים בתחום המזון.',
    categories: ['חד פעמי', 'אריזות', 'מוצרי נייר'],
    phone: '08-555-0112',
    whatsappUrl: 'https://wa.me/97285550112',
    websiteUrl: '/suppliers/ordan-packaging',
    minimumOrder: 350,
    deliveryDays: ['א׳', 'ג׳', 'ד׳'],
    cityCoverage: ['קצרין', 'צפת', 'נתניה', 'תל אביב', 'ירושלים', 'באר שבע'],
    regionIds: ['golan', 'upper-galilee', 'sharon', 'tel-aviv-center', 'jerusalem-area', 'judea-samaria', 'north-negev'],
    isRecommended: true,
    isVerified: true,
  },
  {
    id: 'johnson-clean',
    slug: 'johnson-clean',
    name: 'Johnson Clean',
    logoUrl: '/ordan-logo.png',
    description: 'מוצרי ניקיון וחיטוי למסעדות, ברים ומטבחים פעילים.',
    categories: ['ניקיון', 'היגיינה', 'כימיקלים'],
    phone: '03-555-0181',
    whatsappUrl: 'https://wa.me/97235550181',
    websiteUrl: '/suppliers/johnson-clean',
    minimumOrder: null,
    deliveryDays: ['א׳', 'ב׳', 'ד׳'],
    cityCoverage: ['תל אביב', 'רמת גן', 'פתח תקווה'],
    regionIds: ['tel-aviv-center'],
    isRecommended: false,
    isVerified: true,
  },
  {
    id: 'cold-chain-pro',
    slug: 'cold-chain-pro',
    name: 'Cold Chain Pro',
    logoUrl: '/ordan-logo.png',
    description: 'אספקה בקירור והקפאה עם בקרת טמפרטורה ותיעוד משלוחים.',
    categories: ['קפואים', 'מוצרי חלב', 'לוגיסטיקה קרה'],
    phone: '08-555-0166',
    whatsappUrl: 'https://wa.me/97285550166',
    websiteUrl: '/suppliers/cold-chain-pro',
    minimumOrder: 1000,
    deliveryDays: ['א׳', 'ד׳'],
    cityCoverage: ['חיפה', 'עפולה', 'אשדוד', 'אשקלון', 'באר שבע'],
    regionIds: ['haifa-krayot', 'valleys', 'shfela', 'north-negev'],
    isRecommended: false,
    isVerified: true,
  },
  {
    id: 'holy-city-dry',
    slug: 'holy-city-dry',
    name: 'Holy City Dry Goods',
    logoUrl: '/ordan-logo.png',
    description: 'ספק מוצרי מזווה יבשים למסעדות, קייטרינג ומטבחים מוסדיים.',
    categories: ['יבשים', 'תבלינים', 'קטניות'],
    phone: '02-555-0133',
    whatsappUrl: 'https://wa.me/97225550133',
    websiteUrl: '/suppliers/holy-city-dry',
    minimumOrder: 400,
    deliveryDays: ['ב׳', 'ה׳'],
    cityCoverage: ['ירושלים', 'בית שמש', 'מעלה אדומים', 'אריאל'],
    regionIds: ['jerusalem-area', 'judea-samaria'],
    isRecommended: false,
    isVerified: true,
  },
  {
    id: 'desert-supply',
    slug: 'desert-supply',
    name: 'Desert Supply',
    logoUrl: '/ordan-logo.png',
    description: 'קו אספקה לעסקים בדרום, כולל מוצרי מזווה, ניקיון וציוד מתכלה.',
    categories: ['יבשים', 'חד פעמי', 'ניקיון'],
    phone: '08-555-0128',
    whatsappUrl: 'https://wa.me/97285550128',
    websiteUrl: '/suppliers/desert-supply',
    minimumOrder: 550,
    deliveryDays: ['א׳', 'ד׳'],
    cityCoverage: ['באר שבע', 'דימונה', 'ירוחם', 'מצפה רמון'],
    regionIds: ['north-negev', 'south-negev'],
    isRecommended: true,
    isVerified: false,
  },
  {
    id: 'galil-fish',
    slug: 'galil-fish',
    name: 'גליל דגים',
    logoUrl: '/ordan-logo.png',
    description: 'דגים טריים וקפואים למסעדות עם חלוקה אזורית בצפון.',
    categories: ['דגים', 'קפואים'],
    phone: '04-555-0121',
    whatsappUrl: 'https://wa.me/97245550121',
    websiteUrl: '/suppliers/galil-fish',
    minimumOrder: 900,
    deliveryDays: ['ג׳', 'ה׳'],
    cityCoverage: ['טבריה', 'צפת', 'כרמיאל', 'עפולה'],
    regionIds: ['golan', 'upper-galilee', 'lower-galilee'],
    isRecommended: false,
    isVerified: true,
  },
  {
    id: 'golan-dairy',
    slug: 'golan-dairy',
    name: 'מחלבת הגולן מוסדי',
    logoUrl: '/ordan-logo.png',
    description: 'מוצרי חלב וגבינות למסעדות, מלונות ובתי קפה בצפון.',
    categories: ['מוצרי חלב', 'גבינות', 'קירור'],
    phone: '04-555-0189',
    whatsappUrl: 'https://wa.me/97245550189',
    websiteUrl: '/suppliers/golan-dairy',
    minimumOrder: 650,
    deliveryDays: ['ב׳', 'ד׳'],
    cityCoverage: ['קצרין', 'צפת', 'טבריה', 'נצרת'],
    regionIds: ['golan', 'lower-galilee'],
    isRecommended: true,
    isVerified: true,
  },
]
